import Head from 'next/head'
import Image from 'next/image'
import React from 'react'

function Hero() {
  return (
    <section>
      <Head>
        <title>Log in | Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='relative min-h-[calc(100vh-72px)]'>
        <Image
          src='/images/hero-background.jpg' 
          layout='fill'
          objectFit='cover'
        />
      </div>
      <div className='flex justify-center items-center'>
        <div className='absolute flex flex-col space-y-3 top-1/4 w-full
        justify-center items-center max-w-screen-sm mx-auto p-8 -mt-16'>
          <Image
              src='/images/cta-logo-one.svg'
              width='600'
              height='150'
              objectFit='contain' 
          />
          <button className='uppercase w-full px-6 py-4 rounded-lg text-xl
            font-extrabold tracking-wide hover:bg-white hover:text-sky-500
            transition duration-700 ease-in-out border-transparent shadow-md 
            shadow-sky-500 bg-[#040714]'>Get all there</button>
            <p className='text-xs text-center'>
              {" "}
              Get Premier Access to Raya and the Last Dragon for an additional fee
              with a Disney+ subscription. As of 03/26/21, the price of Disney+
              and The Disney Bundle will increase by $
            </p>
            <Image
            src='/images/cta-logo-two.png'
            width='600'
            height='70'
            objectFit='contain' 
            />
        </div>
      </div>
    </section>
  )
}

export default Hero